#!/usr/bin/env python3
"""Generate a C++ translation unit embedding a stable list of repo files.

Determinism rules:
- Paths are normalized to forward slashes.
- The list file order is preserved; keep it stable-sorted.
- We embed raw bytes (no external compression dependency). Repository
  packaging (zip) provides compression; the substrate performs spectral
  collapse into carrier harmonics at runtime.
"""

from __future__ import annotations

import argparse
import pathlib


def bytes_to_cpp_u8(data: bytes) -> str:
    parts = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        parts.append(", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n    ".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--list", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--namespace", default="EigenWare")
    args = ap.parse_args()

    root = pathlib.Path(args.root).resolve()
    list_path = pathlib.Path(args.list).resolve()
    out_path = pathlib.Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rels: list[str] = []
    for line in list_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        rels.append(line.replace("\\", "/"))

    blobs = []
    for rel in rels:
        p = (root / rel).resolve()
        if not p.exists() or not p.is_file():
            raise SystemExit(f"Missing file: {rel} -> {p}")
        raw = p.read_bytes()
        # No hashing / cryptography allowed in this project.
        # Identity is derived at runtime via 9D coord_sig (deterministic byte moments),
        # not via any digest.
        blobs.append((rel, raw))

    ns = args.namespace
    lines = []
    lines.append("// Auto-generated by scripts/anchorize_files.py. DO NOT EDIT.\n")
    lines.append("#include <cstdint>\n")
    lines.append("#include <vector>\n")
    lines.append("#include \"anchor_pack.hpp\"\n\n")
    lines.append(f"namespace {ns} {{\n")
    lines.append("namespace AnchorPackGen {\n")
    lines.append("struct Blob { const char* relpath; const uint8_t* data; uint32_t size; uint32_t raw_size; };\n")

    for i, (rel, raw) in enumerate(blobs):
        arr = bytes_to_cpp_u8(raw)
        lines.append(f"static const uint8_t blob_{i}_u8[] = {{\n    {arr}\n}};\n")

    lines.append("static const Blob g_blobs[] = {\n")
    for i, (rel, raw) in enumerate(blobs):
        lines.append(f"    {{\"{rel}\", blob_{i}_u8, (uint32_t)sizeof(blob_{i}_u8), (uint32_t){len(raw)}}},\n")
    lines.append("};\n")
    lines.append("static const uint32_t g_blob_count = (uint32_t)(sizeof(g_blobs)/sizeof(g_blobs[0]));\n")

    lines.append("void get_embedded_blobs(std::vector<AnchorPackBlob>& out) {\n")
    lines.append("    out.clear();\n")
    lines.append("    out.reserve(g_blob_count);\n")
    lines.append("    for (uint32_t i = 0; i < g_blob_count; ++i) {\n")
    lines.append("        AnchorPackBlob b;\n")
    lines.append("        b.relpath_utf8 = g_blobs[i].relpath;\n")
    lines.append("        b.comp_bytes_u8.assign(g_blobs[i].data, g_blobs[i].data + g_blobs[i].size);\n")
    lines.append("        b.raw_size_u32 = g_blobs[i].raw_size;\n")
    lines.append("        // No digests or hashing.\n")
    lines.append("        out.push_back(std::move(b));\n")
    lines.append("    }\n")
    lines.append("}\n")

    lines.append("} // namespace AnchorPackGen\n")
    lines.append(f"}} // namespace {ns}\n")

    out_path.write_text("".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
