#include <iostream>
#include <fstream>
#include <filesystem>
#include <vector>
#include <string>
#include <sstream>
#include <cstdint>
#include <algorithm>
#include <iomanip>

namespace fs = std::filesystem;

std::string bytes_to_cpp_u8(const std::vector<uint8_t>& data) {
    std::stringstream ss;
    for (size_t i = 0; i < data.size(); i += 16) {
        if (i > 0) ss << ",\n    ";
        size_t end = std::min(i + 16, data.size());
        for (size_t j = i; j < end; ++j) {
            if (j > i) ss << ", ";
            ss << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(data[j]);
        }
    }
    return ss.str();
}

int main(int argc, char* argv[]) {
    if (argc < 7 || argc > 9) {
        std::cerr << "Usage: " << argv[0] << " --root <root_dir> --list <list_file> --out <output_file> [--namespace <namespace>]\n";
        return 1;
    }

    fs::path root_path;
    fs::path list_path;
    fs::path out_path;
    std::string ns = "EigenWare";

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--root" && i + 1 < argc) {
            root_path = argv[++i];
        } else if (arg == "--list" && i + 1 < argc) {
            list_path = argv[++i];
        } else if (arg == "--out" && i + 1 < argc) {
            out_path = argv[++i];
        } else if (arg == "--namespace" && i + 1 < argc) {
            ns = argv[++i];
        }
    }

    if (root_path.empty() || list_path.empty() || out_path.empty()) {
        std::cerr << "Error: --root, --list, and --out are required\n";
        return 1;
    }

    root_path = fs::absolute(root_path);
    list_path = fs::absolute(list_path);
    out_path = fs::absolute(out_path);

    // Create output directory if it doesn't exist
    fs::create_directories(out_path.parent_path());

    // Read the list file
    std::ifstream list_file(list_path);
    if (!list_file) {
        std::cerr << "Error: Cannot open list file: " << list_path << "\n";
        return 1;
    }

    std::vector<std::string> rels;
    std::string line;
    while (std::getline(list_file, line)) {
        // Trim whitespace
        line.erase(line.begin(), std::find_if(line.begin(), line.end(), [](unsigned char ch) {
            return !std::isspace(ch);
        }));
        line.erase(std::find_if(line.rbegin(), line.rend(), [](unsigned char ch) {
            return !std::isspace(ch);
        }).base(), line.end());

        if (!line.empty() && line[0] != '#') {
            // Normalize to forward slashes
            std::replace(line.begin(), line.end(), '\\', '/');
            rels.push_back(line);
        }
    }

    // Read all blob files
    struct BlobInfo {
        std::string relpath;
        std::vector<uint8_t> data;
    };
    std::vector<BlobInfo> blobs;

    for (const auto& rel : rels) {
        fs::path file_path = root_path / rel;
        file_path = fs::absolute(file_path);

        if (!fs::exists(file_path) || !fs::is_regular_file(file_path)) {
            std::cerr << "Error: Missing file: " << rel << " -> " << file_path << "\n";
            return 1;
        }

        std::ifstream file(file_path, std::ios::binary);
        if (!file) {
            std::cerr << "Error: Cannot open file: " << file_path << "\n";
            return 1;
        }

        std::vector<uint8_t> data((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
        blobs.push_back({rel, std::move(data)});
    }

    // Generate C++ code
    std::stringstream output;
    output << "// Auto-generated by tools/anchorize_files.cpp. DO NOT EDIT.\n";
    output << "#include <cstdint>\n";
    output << "#include <vector>\n";
    output << "#include \"anchor_pack.hpp\"\n\n";
    output << "namespace " << ns << " {\n";
    output << "namespace AnchorPackGen {\n";
    output << "struct Blob { const char* relpath; const uint8_t* data; uint32_t size; uint32_t raw_size; };\n";

    for (size_t i = 0; i < blobs.size(); ++i) {
        const auto& blob = blobs[i];
        std::string arr = bytes_to_cpp_u8(blob.data);
        output << "static const uint8_t blob_" << i << "_u8[] = {\n    " << arr << "\n};\n";
    }

    output << "static const Blob g_blobs[] = {\n";
    for (size_t i = 0; i < blobs.size(); ++i) {
        const auto& blob = blobs[i];
        output << "    {\"" << blob.relpath << "\", blob_" << i << "_u8, (uint32_t)sizeof(blob_" << i << "_u8), (uint32_t)" << blob.data.size() << "},\n";
    }
    output << "};\n";
    output << "static const uint32_t g_blob_count = (uint32_t)(sizeof(g_blobs)/sizeof(g_blobs[0]));\n";

    output << "void get_embedded_blobs(std::vector<AnchorPackBlob>& out) {\n";
    output << "    out.clear();\n";
    output << "    out.reserve(g_blob_count);\n";
    output << "    for (uint32_t i = 0; i < g_blob_count; ++i) {\n";
    output << "        AnchorPackBlob b;\n";
    output << "        b.relpath_utf8 = g_blobs[i].relpath;\n";
    output << "        b.comp_bytes_u8.assign(g_blobs[i].data, g_blobs[i].data + g_blobs[i].size);\n";
    output << "        b.raw_size_u32 = g_blobs[i].raw_size;\n";
    output << "        // No digests or hashing.\n";
    output << "        out.push_back(std::move(b));\n";
    output << "    }\n";
    output << "}\n";

    output << "} // namespace AnchorPackGen\n";
    output << "} // namespace " << ns << "\n";

    // Write output file
    std::ofstream out_file(out_path);
    if (!out_file) {
        std::cerr << "Error: Cannot create output file: " << out_path << "\n";
        return 1;
    }
    out_file << output.str();
    out_file.close();

    std::cout << "Generated anchor pack: " << out_path << " (" << blobs.size() << " files)\n";
    return 0;
}
